project:
  type: website
  output-dir: docs

website:
  title: "Fichas de Riesgo UNGRD"
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Departamentos"
        contents: "fichas/**/*.qmd"

format:
  html:
    theme: [cosmo, custom.scss]
    title-block-banner: "#ED1E6"
    toc: true
    df-print: paged      # Hace que las tablas muy largas tengan paginación
    html-table-processing: none # Evita que Quarto rompa las tablas complejas de Markdown
