---
title: "Presentación"
subtitle: "Ficha Departamental: Cordoba"
author:
  - name: "Unidad Nacional para la Gestión del Riesgo de Desastres"
    affiliations:
      - name: "Subdirección para el Conocimiento del Riesgo - UNGRD"
date: "2026"
title-block-banner: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=2072"
title-block-banner-color: "black"
---

::: {.bg-presentacion}
# Presentación

La Ficha Departamental de Caracterización de Escenarios de Riesgo del
Departamento de Cordoba se constituye en un insumo técnico elaborado
a partir de la consolidación de información institucional existente, con el
propósito de fortalecer los procesos de planificación territorial y de gestión
del riesgo de desastres.
Este documento está dirigido a tomadores de decisión —alcaldes,
gobernadores, coordinadores departamentales y municipales de gestión
del riesgo de desastres—, así como a la población académica y a los
profesionales de apoyo de las administraciones públicas, quienes requieren
información veraz, clara y actualizada para orientar acciones preventivas y
de reducción del riesgo en el territorio.
La ficha íntegra, mediante gráficas, mapas e infografías, los principales
elementos relacionados con las determinantes ambientales, socioeconómicas
y las amenazas de origen natural, socio-natural y tecnológico (NaTech), que
inciden en la seguridad y el bienestar de la población. De esta manera, se
configura como una herramienta estratégica para la toma de decisiones
fundamentadas, la gestión prospectiva y correctiva del riesgo, y la
construcción de territorios más seguros, sostenibles y resilientes.
:::
